- name: "Play to Install, Configure and Intiailize content on Apache web server"
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    apache_test_message: "THIS IS AN APACHE WEB SERVICE"
  tasks:
  - name: "Install httpd Apache web server"
    yum:
      name: httpd
      state: latest
  - name: "Setup the content"
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
  - name: "Enable and start Service"
    service:
      name: httpd
      state: started
      enabled: yes
